// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package sentry.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the Sentry module
	public static boolean afterStartup(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		return (java.lang.Boolean) Core.microflowCall("Sentry.AfterStartup").withParams(params).execute(context);
	}
	public static sentry.proxies.NativeConfiguration dS_GetGenericNativeConfiguration(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("Sentry.DS_GetGenericNativeConfiguration").withParams(params).execute(context);
		return result == null ? null : sentry.proxies.NativeConfiguration.initialize(context, result);
	}
	public static sentry.proxies.RuntimeConfiguration dS_GetRuntimeConfiguration(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("Sentry.DS_GetRuntimeConfiguration").withParams(params).execute(context);
		return result == null ? null : sentry.proxies.RuntimeConfiguration.initialize(context, result);
	}
	public static sentry.proxies.WebConfiguration dS_GetWebConfiguration(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("Sentry.DS_GetWebConfiguration").withParams(params).execute(context);
		return result == null ? null : sentry.proxies.WebConfiguration.initialize(context, result);
	}
	public static void iVK_NewUserNativeConfiguration(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Sentry.IVK_NewUserNativeConfiguration").withParams(params).execute(context);
	}
	public static void iVK_SaveNativeConfiguration(IContext context, sentry.proxies.NativeConfiguration _nativeConfiguration)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("NativeConfiguration", _nativeConfiguration == null ? null : _nativeConfiguration.getMendixObject());
		Core.microflowCall("Sentry.IVK_SaveNativeConfiguration").withParams(params).execute(context);
	}
	public static void iVK_SaveRuntimeConfiguration(IContext context, sentry.proxies.RuntimeConfiguration _runtimeConfiguration)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("RuntimeConfiguration", _runtimeConfiguration == null ? null : _runtimeConfiguration.getMendixObject());
		Core.microflowCall("Sentry.IVK_SaveRuntimeConfiguration").withParams(params).execute(context);
	}
	public static void iVK_SaveWebConfiguration(IContext context, sentry.proxies.WebConfiguration _webConfiguration)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("WebConfiguration", _webConfiguration == null ? null : _webConfiguration.getMendixObject());
		Core.microflowCall("Sentry.IVK_SaveWebConfiguration").withParams(params).execute(context);
	}
}
