// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
import * as SentryRNAPI from "@sentry/react-native";
import * as SentryWebAPI from "@sentry/browser";
// END EXTRA CODE

/**
 * See https://docs.sentry.io/platforms/javascript/enriching-events/breadcrumbs/
 * @param {string} category
 * @param {string} message
 * @param {"Sentry.Severity.critical"|"Sentry.Severity.fatal"|"Sentry.Severity.error"|"Sentry.Severity.warning"|"Sentry.Severity.log"|"Sentry.Severity.info"|"Sentry.Severity.debug"} level
 * @returns {Promise.<void>}
 */
export async function AddBreadcrumb(category, message, level) {
	// BEGIN USER CODE
	var SentryAPI = null;
	if (navigator && navigator.product === "ReactNative" && !navigator.geolocation) {
        SentryAPI = SentryRNAPI;
    } else {
		SentryAPI = SentryWebAPI;
	}

	SentryAPI.addBreadcrumb({
		category: category,
		message: message,
		level: SentryAPI.Severity.fromString(message)
	});
	// END USER CODE
}
