// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
import * as SentryRNAPI from "@sentry/react-native";
import * as SentryWebAPI from "@sentry/browser";
// END EXTRA CODE

/**
 * See https://docs.sentry.io/platforms/javascript/enriching-events/tags/
 * @param {string} key
 * @param {string} value
 * @returns {Promise.<void>}
 */
export async function AddTag(key, value) {
	// BEGIN USER CODE
	var SentryAPI = null;
	if (navigator && navigator.product === "ReactNative" && !navigator.geolocation) {
        SentryAPI = SentryRNAPI;
    } else {
		SentryAPI = SentryWebAPI;
	}
	SentryAPI.setTag(key, value);
	// END USER CODE
}
