// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
import * as SentryAPI from "@sentry/react-native";
// END EXTRA CODE

/**
 * @param {Big} transactionId
 * @returns {Promise.<void>}
 */
export async function Native_FinishTransaction(transactionId) {
	// BEGIN USER CODE
	let transaction = GLOBAL.sentryTransactions["" + transactionId];
	if (!transaction) {
		console.warn("Expected to finish transaction " + transactionId + " but it wasn't found.")
		return;
	}
	transaction.finish();
	delete GLOBAL.sentryTransactions["" + transactionId];
	// END USER CODE
}
