// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
import * as SentryRNAPI from "@sentry/react-native";
import * as SentryWebAPI from "@sentry/browser";
// END EXTRA CODE

/**
 * @param {string} _id - Your internal identifier for the user.
 * @param {string} username - The username. Typically used as a better label than the internal id.
 * @param {string} email - An alternative, or addition, to the username. Sentry is aware of email addresses and can display things such as Gravatars and unlock messaging capabilities.
 * @param {string} ip_address - The user's IP address. If the user is unauthenticated, Sentry uses the IP address as a unique identifier for the user. Sentry will attempt to pull this from the HTTP request data, if available.
 * @returns {Promise.<void>}
 */
export async function SetUser(_id, username, email, ip_address) {
	// BEGIN USER CODE
	var SentryAPI = null;
	if (navigator && navigator.product === "ReactNative" && !navigator.geolocation) {
        SentryAPI = SentryRNAPI;
    } else {
		SentryAPI = SentryWebAPI;
	}

	SentryAPI.setUser({
		id: _id,
		username: username,
		email: email,
		ip_address: ip_address
	});

	console.info("[Sentry] User information set.");
	// END USER CODE
}
