// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
import * as SentryRNAPI from "@sentry/react-native";
import * as SentryWebAPI from "@sentry/browser";
import * as SentryTracing from "@sentry/tracing";
// END EXTRA CODE

/**
 * @param {string} name
 * @param {string} op
 * @returns {Promise.<Big>}
 */
export async function StartTransaction(name, op) {
	// BEGIN USER CODE
	var SentryAPI = null;
	var SCOPE = null;
	var bla = SentryTracing;

	if (navigator && navigator.product === "ReactNative") {
				SCOPE = GLOBAL;
        SentryAPI = SentryRNAPI;
    } else {
				SentryAPI = SentryWebAPI;
				SCOPE = window;
	}

	if (!SCOPE.hasOwnProperty("sentryTransactionChildren"))
		SCOPE.sentryTransactionChildren = {};
	if (!SCOPE.hasOwnProperty("sentryTransactions"))
		SCOPE.sentryTransactions = {};


	let newId = Object.keys(SCOPE.sentryTransactions).length;
	SCOPE.sentryTransactions["" + newId] = SentryAPI.startTransaction({ 
		name: name,
		op: op
	});
	return newId;
	// END USER CODE
}
