// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
GLOBAL.sentryTransactionChildren = {};
// END EXTRA CODE

/**
 * @param {Big} transactionId
 * @param {string} op
 * @param {string} description
 * @returns {Promise.<Big>}
 */
export async function StartChild(transactionId, op, description) {
	// BEGIN USER CODE
	let transaction = GLOBAL.sentryTransactions["" + transactionId];
	let newId = Object.keys(GLOBAL.sentryTransactionChildren).length;
	GLOBAL.sentryTransactionChildren["" + newId] = transaction.startChild({
		op: op,
		description: description
	});
	return newId;
	// END USER CODE
}
