// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package sentry.proxies;

public enum MendixLogLevel
{
	TRACE(new java.lang.String[][] { new java.lang.String[] { "en_US", "Trace" } }),
	DEBUG(new java.lang.String[][] { new java.lang.String[] { "en_US", "Debug" } }),
	INFO(new java.lang.String[][] { new java.lang.String[] { "en_US", "Info" } }),
	WARNING(new java.lang.String[][] { new java.lang.String[] { "en_US", "Warning" } }),
	ERROR(new java.lang.String[][] { new java.lang.String[] { "en_US", "Error" } }),
	CRITICAL(new java.lang.String[][] { new java.lang.String[] { "en_US", "Critical" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private MendixLogLevel(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
