// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package sentry.proxies;

public class NativeConfiguration
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject nativeConfigurationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Sentry.NativeConfiguration";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Enabled("Enabled"),
		DSN("DSN"),
		Configuration("Configuration"),
		Scope("Scope"),
		NativeConfiguration_User("Sentry.NativeConfiguration_User");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public NativeConfiguration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Sentry.NativeConfiguration"));
	}

	protected NativeConfiguration(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject nativeConfigurationMendixObject)
	{
		if (nativeConfigurationMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Sentry.NativeConfiguration", nativeConfigurationMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Sentry.NativeConfiguration");

		this.nativeConfigurationMendixObject = nativeConfigurationMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'NativeConfiguration.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static sentry.proxies.NativeConfiguration initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return sentry.proxies.NativeConfiguration.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static sentry.proxies.NativeConfiguration initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new sentry.proxies.NativeConfiguration(context, mendixObject);
	}

	public static sentry.proxies.NativeConfiguration load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return sentry.proxies.NativeConfiguration.initialize(context, mendixObject);
	}

	public static java.util.List<sentry.proxies.NativeConfiguration> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<sentry.proxies.NativeConfiguration> result = new java.util.ArrayList<sentry.proxies.NativeConfiguration>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Sentry.NativeConfiguration" + xpathConstraint))
			result.add(sentry.proxies.NativeConfiguration.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Enabled
	 */
	public final java.lang.Boolean getEnabled()
	{
		return getEnabled(getContext());
	}

	/**
	 * @param context
	 * @return value of Enabled
	 */
	public final java.lang.Boolean getEnabled(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Enabled.toString());
	}

	/**
	 * Set value of Enabled
	 * @param enabled
	 */
	public final void setEnabled(java.lang.Boolean enabled)
	{
		setEnabled(getContext(), enabled);
	}

	/**
	 * Set value of Enabled
	 * @param context
	 * @param enabled
	 */
	public final void setEnabled(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean enabled)
	{
		getMendixObject().setValue(context, MemberNames.Enabled.toString(), enabled);
	}

	/**
	 * @return value of DSN
	 */
	public final java.lang.String getDSN()
	{
		return getDSN(getContext());
	}

	/**
	 * @param context
	 * @return value of DSN
	 */
	public final java.lang.String getDSN(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DSN.toString());
	}

	/**
	 * Set value of DSN
	 * @param dsn
	 */
	public final void setDSN(java.lang.String dsn)
	{
		setDSN(getContext(), dsn);
	}

	/**
	 * Set value of DSN
	 * @param context
	 * @param dsn
	 */
	public final void setDSN(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String dsn)
	{
		getMendixObject().setValue(context, MemberNames.DSN.toString(), dsn);
	}

	/**
	 * @return value of Configuration
	 */
	public final java.lang.String getConfiguration()
	{
		return getConfiguration(getContext());
	}

	/**
	 * @param context
	 * @return value of Configuration
	 */
	public final java.lang.String getConfiguration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Configuration.toString());
	}

	/**
	 * Set value of Configuration
	 * @param configuration
	 */
	public final void setConfiguration(java.lang.String configuration)
	{
		setConfiguration(getContext(), configuration);
	}

	/**
	 * Set value of Configuration
	 * @param context
	 * @param configuration
	 */
	public final void setConfiguration(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String configuration)
	{
		getMendixObject().setValue(context, MemberNames.Configuration.toString(), configuration);
	}

	/**
	 * Set value of Scope
	 * @param scope
	 */
	public final sentry.proxies.NativeConfigurationScope getScope()
	{
		return getScope(getContext());
	}

	/**
	 * @param context
	 * @return value of Scope
	 */
	public final sentry.proxies.NativeConfigurationScope getScope(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Scope.toString());
		if (obj == null)
			return null;

		return sentry.proxies.NativeConfigurationScope.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Scope
	 * @param scope
	 */
	public final void setScope(sentry.proxies.NativeConfigurationScope scope)
	{
		setScope(getContext(), scope);
	}

	/**
	 * Set value of Scope
	 * @param context
	 * @param scope
	 */
	public final void setScope(com.mendix.systemwideinterfaces.core.IContext context, sentry.proxies.NativeConfigurationScope scope)
	{
		if (scope != null)
			getMendixObject().setValue(context, MemberNames.Scope.toString(), scope.toString());
		else
			getMendixObject().setValue(context, MemberNames.Scope.toString(), null);
	}

	/**
	 * @return value of NativeConfiguration_User
	 */
	public final system.proxies.User getNativeConfiguration_User() throws com.mendix.core.CoreException
	{
		return getNativeConfiguration_User(getContext());
	}

	/**
	 * @param context
	 * @return value of NativeConfiguration_User
	 */
	public final system.proxies.User getNativeConfiguration_User(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.User result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.NativeConfiguration_User.toString());
		if (identifier != null)
			result = system.proxies.User.load(context, identifier);
		return result;
	}

	/**
	 * Set value of NativeConfiguration_User
	 * @param nativeconfiguration_user
	 */
	public final void setNativeConfiguration_User(system.proxies.User nativeconfiguration_user)
	{
		setNativeConfiguration_User(getContext(), nativeconfiguration_user);
	}

	/**
	 * Set value of NativeConfiguration_User
	 * @param context
	 * @param nativeconfiguration_user
	 */
	public final void setNativeConfiguration_User(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.User nativeconfiguration_user)
	{
		if (nativeconfiguration_user == null)
			getMendixObject().setValue(context, MemberNames.NativeConfiguration_User.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.NativeConfiguration_User.toString(), nativeconfiguration_user.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return nativeConfigurationMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final sentry.proxies.NativeConfiguration that = (sentry.proxies.NativeConfiguration) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Sentry.NativeConfiguration";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
