// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package sentry.proxies;

public class RuntimeConfiguration
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject runtimeConfigurationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Sentry.RuntimeConfiguration";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Enabled("Enabled"),
		DSN("DSN"),
		RedirectMendixLog("RedirectMendixLog"),
		Debug("Debug"),
		Environment("Environment"),
		SampleRate("SampleRate"),
		TracesSampleRate("TracesSampleRate"),
		AttachStacktrace("AttachStacktrace"),
		DiagnosticLevel("DiagnosticLevel"),
		LogLevel("LogLevel");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RuntimeConfiguration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected RuntimeConfiguration(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject runtimeConfigurationMendixObject)
	{
		if (runtimeConfigurationMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, runtimeConfigurationMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.runtimeConfigurationMendixObject = runtimeConfigurationMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'RuntimeConfiguration.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static sentry.proxies.RuntimeConfiguration initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return sentry.proxies.RuntimeConfiguration.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static sentry.proxies.RuntimeConfiguration initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new sentry.proxies.RuntimeConfiguration(context, mendixObject);
	}

	public static sentry.proxies.RuntimeConfiguration load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return sentry.proxies.RuntimeConfiguration.initialize(context, mendixObject);
	}

	public static java.util.List<sentry.proxies.RuntimeConfiguration> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> sentry.proxies.RuntimeConfiguration.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Enabled
	 */
	public final java.lang.Boolean getEnabled()
	{
		return getEnabled(getContext());
	}

	/**
	 * @param context
	 * @return value of Enabled
	 */
	public final java.lang.Boolean getEnabled(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Enabled.toString());
	}

	/**
	 * Set value of Enabled
	 * @param enabled
	 */
	public final void setEnabled(java.lang.Boolean enabled)
	{
		setEnabled(getContext(), enabled);
	}

	/**
	 * Set value of Enabled
	 * @param context
	 * @param enabled
	 */
	public final void setEnabled(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean enabled)
	{
		getMendixObject().setValue(context, MemberNames.Enabled.toString(), enabled);
	}

	/**
	 * @return value of DSN
	 */
	public final java.lang.String getDSN()
	{
		return getDSN(getContext());
	}

	/**
	 * @param context
	 * @return value of DSN
	 */
	public final java.lang.String getDSN(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DSN.toString());
	}

	/**
	 * Set value of DSN
	 * @param dsn
	 */
	public final void setDSN(java.lang.String dsn)
	{
		setDSN(getContext(), dsn);
	}

	/**
	 * Set value of DSN
	 * @param context
	 * @param dsn
	 */
	public final void setDSN(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String dsn)
	{
		getMendixObject().setValue(context, MemberNames.DSN.toString(), dsn);
	}

	/**
	 * @return value of RedirectMendixLog
	 */
	public final java.lang.Boolean getRedirectMendixLog()
	{
		return getRedirectMendixLog(getContext());
	}

	/**
	 * @param context
	 * @return value of RedirectMendixLog
	 */
	public final java.lang.Boolean getRedirectMendixLog(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.RedirectMendixLog.toString());
	}

	/**
	 * Set value of RedirectMendixLog
	 * @param redirectmendixlog
	 */
	public final void setRedirectMendixLog(java.lang.Boolean redirectmendixlog)
	{
		setRedirectMendixLog(getContext(), redirectmendixlog);
	}

	/**
	 * Set value of RedirectMendixLog
	 * @param context
	 * @param redirectmendixlog
	 */
	public final void setRedirectMendixLog(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean redirectmendixlog)
	{
		getMendixObject().setValue(context, MemberNames.RedirectMendixLog.toString(), redirectmendixlog);
	}

	/**
	 * @return value of Debug
	 */
	public final java.lang.Boolean getDebug()
	{
		return getDebug(getContext());
	}

	/**
	 * @param context
	 * @return value of Debug
	 */
	public final java.lang.Boolean getDebug(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Debug.toString());
	}

	/**
	 * Set value of Debug
	 * @param debug
	 */
	public final void setDebug(java.lang.Boolean debug)
	{
		setDebug(getContext(), debug);
	}

	/**
	 * Set value of Debug
	 * @param context
	 * @param debug
	 */
	public final void setDebug(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean debug)
	{
		getMendixObject().setValue(context, MemberNames.Debug.toString(), debug);
	}

	/**
	 * @return value of Environment
	 */
	public final java.lang.String getEnvironment()
	{
		return getEnvironment(getContext());
	}

	/**
	 * @param context
	 * @return value of Environment
	 */
	public final java.lang.String getEnvironment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Environment.toString());
	}

	/**
	 * Set value of Environment
	 * @param environment
	 */
	public final void setEnvironment(java.lang.String environment)
	{
		setEnvironment(getContext(), environment);
	}

	/**
	 * Set value of Environment
	 * @param context
	 * @param environment
	 */
	public final void setEnvironment(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String environment)
	{
		getMendixObject().setValue(context, MemberNames.Environment.toString(), environment);
	}

	/**
	 * @return value of SampleRate
	 */
	public final java.math.BigDecimal getSampleRate()
	{
		return getSampleRate(getContext());
	}

	/**
	 * @param context
	 * @return value of SampleRate
	 */
	public final java.math.BigDecimal getSampleRate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.SampleRate.toString());
	}

	/**
	 * Set value of SampleRate
	 * @param samplerate
	 */
	public final void setSampleRate(java.math.BigDecimal samplerate)
	{
		setSampleRate(getContext(), samplerate);
	}

	/**
	 * Set value of SampleRate
	 * @param context
	 * @param samplerate
	 */
	public final void setSampleRate(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal samplerate)
	{
		getMendixObject().setValue(context, MemberNames.SampleRate.toString(), samplerate);
	}

	/**
	 * @return value of TracesSampleRate
	 */
	public final java.math.BigDecimal getTracesSampleRate()
	{
		return getTracesSampleRate(getContext());
	}

	/**
	 * @param context
	 * @return value of TracesSampleRate
	 */
	public final java.math.BigDecimal getTracesSampleRate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.TracesSampleRate.toString());
	}

	/**
	 * Set value of TracesSampleRate
	 * @param tracessamplerate
	 */
	public final void setTracesSampleRate(java.math.BigDecimal tracessamplerate)
	{
		setTracesSampleRate(getContext(), tracessamplerate);
	}

	/**
	 * Set value of TracesSampleRate
	 * @param context
	 * @param tracessamplerate
	 */
	public final void setTracesSampleRate(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal tracessamplerate)
	{
		getMendixObject().setValue(context, MemberNames.TracesSampleRate.toString(), tracessamplerate);
	}

	/**
	 * @return value of AttachStacktrace
	 */
	public final java.lang.Boolean getAttachStacktrace()
	{
		return getAttachStacktrace(getContext());
	}

	/**
	 * @param context
	 * @return value of AttachStacktrace
	 */
	public final java.lang.Boolean getAttachStacktrace(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.AttachStacktrace.toString());
	}

	/**
	 * Set value of AttachStacktrace
	 * @param attachstacktrace
	 */
	public final void setAttachStacktrace(java.lang.Boolean attachstacktrace)
	{
		setAttachStacktrace(getContext(), attachstacktrace);
	}

	/**
	 * Set value of AttachStacktrace
	 * @param context
	 * @param attachstacktrace
	 */
	public final void setAttachStacktrace(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean attachstacktrace)
	{
		getMendixObject().setValue(context, MemberNames.AttachStacktrace.toString(), attachstacktrace);
	}

	/**
	 * Set value of DiagnosticLevel
	 * @param diagnosticlevel
	 */
	public final sentry.proxies.SentryLevel getDiagnosticLevel()
	{
		return getDiagnosticLevel(getContext());
	}

	/**
	 * @param context
	 * @return value of DiagnosticLevel
	 */
	public final sentry.proxies.SentryLevel getDiagnosticLevel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.DiagnosticLevel.toString());
		if (obj == null) {
			return null;
		}
		return sentry.proxies.SentryLevel.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of DiagnosticLevel
	 * @param diagnosticlevel
	 */
	public final void setDiagnosticLevel(sentry.proxies.SentryLevel diagnosticlevel)
	{
		setDiagnosticLevel(getContext(), diagnosticlevel);
	}

	/**
	 * Set value of DiagnosticLevel
	 * @param context
	 * @param diagnosticlevel
	 */
	public final void setDiagnosticLevel(com.mendix.systemwideinterfaces.core.IContext context, sentry.proxies.SentryLevel diagnosticlevel)
	{
		if (diagnosticlevel != null) {
			getMendixObject().setValue(context, MemberNames.DiagnosticLevel.toString(), diagnosticlevel.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.DiagnosticLevel.toString(), null);
		}
	}

	/**
	 * Set value of LogLevel
	 * @param loglevel
	 */
	public final sentry.proxies.MendixLogLevel getLogLevel()
	{
		return getLogLevel(getContext());
	}

	/**
	 * @param context
	 * @return value of LogLevel
	 */
	public final sentry.proxies.MendixLogLevel getLogLevel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.LogLevel.toString());
		if (obj == null) {
			return null;
		}
		return sentry.proxies.MendixLogLevel.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of LogLevel
	 * @param loglevel
	 */
	public final void setLogLevel(sentry.proxies.MendixLogLevel loglevel)
	{
		setLogLevel(getContext(), loglevel);
	}

	/**
	 * Set value of LogLevel
	 * @param context
	 * @param loglevel
	 */
	public final void setLogLevel(com.mendix.systemwideinterfaces.core.IContext context, sentry.proxies.MendixLogLevel loglevel)
	{
		if (loglevel != null) {
			getMendixObject().setValue(context, MemberNames.LogLevel.toString(), loglevel.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.LogLevel.toString(), null);
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return runtimeConfigurationMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final sentry.proxies.RuntimeConfiguration that = (sentry.proxies.RuntimeConfiguration) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
