// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package sentry.proxies;

public enum Severity
{
	critical(new java.lang.String[][] { new java.lang.String[] { "en_US", "Critical" } }),
	fatal(new java.lang.String[][] { new java.lang.String[] { "en_US", "Fatal" } }),
	error(new java.lang.String[][] { new java.lang.String[] { "en_US", "Error" } }),
	warning(new java.lang.String[][] { new java.lang.String[] { "en_US", "Warning" } }),
	log(new java.lang.String[][] { new java.lang.String[] { "en_US", "Log" } }),
	info(new java.lang.String[][] { new java.lang.String[] { "en_US", "Info" } }),
	debug(new java.lang.String[][] { new java.lang.String[] { "en_US", "Debug" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private Severity(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
