// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package sentry.actions;

import java.net.URL;
import com.mendix.core.Core;
import com.mendix.logging.LogLevel;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import io.sentry.Sentry;
import sentry.impl.SentryLogSubscriber;
import sentry.impl.SentryLogger;

public class InitializeSentry extends CustomJavaAction<java.lang.Void>
{
	public InitializeSentry(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		URL url = new URL(Core.getConfiguration().getApplicationRootUrl());
		
		Sentry.init(options -> {
			options.setEnableExternalConfiguration(true);
			options.setServerName(url.getHost());
			options.setRelease(Core.getModelVersion());
			options.setLogger(new SentryLogger());
 			options.setTracesSampleRate(1d); // FIX THIS!!
		});
		
		if (System.getenv("CF_INSTANCE_INDEX") != null) {
			Sentry.setTag("instance", System.getenv("CF_INSTANCE_INDEX"));
		}
		
		Sentry.setTag("runtime.version", Core.getConfiguration().RUNTIME_VERSION.toString());
		Core.registerLogSubscriber(new SentryLogSubscriber(LogLevel.INFO));
		
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "InitializeSentry";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
