// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package sentry.actions;

import java.util.Stack;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import io.sentry.ISpan;
import io.sentry.SpanStatus;
import sentry.impl.SentryConstants;

public class Runtime_FinishChild extends CustomJavaAction<java.lang.Void>
{
	private java.lang.Boolean didError;

	public Runtime_FinishChild(IContext context, java.lang.Boolean didError)
	{
		super(context);
		this.didError = didError;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		ILogNode logger = Core.getLogger(SentryConstants.LOGNODE);
		Object childStackObject = getContext().getData().get(SentryConstants.CHILD_KEY);
		if (childStackObject == null || !(childStackObject instanceof Stack)) {
			logger.warn("Start a Sentry child first.");
			return null;
		}
		Stack<ISpan> childStack = (Stack<ISpan>) childStackObject;
		
		ISpan child = (ISpan) childStack.pop();
		child.finish(didError ? SpanStatus.INTERNAL_ERROR : SpanStatus.OK);
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Runtime_FinishChild";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
