// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package sentry.actions;

import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import io.sentry.ITransaction;
import io.sentry.SpanStatus;
import sentry.impl.SentryConstants;

public class Runtime_FinishTransaction extends CustomJavaAction<java.lang.Void>
{
	private java.lang.Boolean didError;

	public Runtime_FinishTransaction(IContext context, java.lang.Boolean didError)
	{
		super(context);
		this.didError = didError;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		Object transactionObject = getContext().getData().get(SentryConstants.TRANSACTION_KEY); 
		if (transactionObject == null || !(transactionObject instanceof ITransaction)) 
			throw new CoreException("Start a Sentry transaction first.");
		ITransaction transaction = (ITransaction) transactionObject;
		transaction.finish(didError ? SpanStatus.INTERNAL_ERROR : SpanStatus.OK);
		getContext().getData().remove(SentryConstants.TRANSACTION_KEY);
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Runtime_FinishTransaction";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
