// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package sentry.actions;

import java.util.Stack;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import io.sentry.ISpan;
import io.sentry.ITransaction;
import sentry.impl.SentryConstants;

public class Runtime_StartChild extends CustomJavaAction<java.lang.Void>
{
	private java.lang.String op;
	private java.lang.String description;

	public Runtime_StartChild(IContext context, java.lang.String op, java.lang.String description)
	{
		super(context);
		this.op = op;
		this.description = description;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		ILogNode logger = Core.getLogger(SentryConstants.LOGNODE);
		Object transactionStackObject = getContext().getData().get(SentryConstants.TRANSACTION_KEY); 
		if (transactionStackObject == null || !(transactionStackObject instanceof Stack)) {
			logger.warn("Start a Sentry transaction first.");
			return null;
		}
		Stack<ITransaction> transactionStack = (Stack<ITransaction>) transactionStackObject;
		Stack<ISpan> childStack; 
		
		if (!getContext().getData().containsKey(SentryConstants.CHILD_KEY)) {
			childStack = new Stack<ISpan>();
			getContext().getData().put(SentryConstants.CHILD_KEY, childStack);
		} else {
			childStack = (Stack<ISpan>) getContext().getData().get(SentryConstants.CHILD_KEY);
		}
		
		ITransaction transaction = (ITransaction) transactionStack.peek();
		ISpan span = transaction.startChild(op, description);
		childStack.push(span);
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Runtime_StartChild";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
