// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package sentry.actions;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

import io.sentry.ISpan;
import sentry.impl.SentryConstants;

public class Runtime_FinishChild extends CustomJavaAction<java.lang.Void>
{
	public Runtime_FinishChild(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		ILogNode logger = Core.getLogger(SentryConstants.LOGNODE);
		Object childObject = getContext().getData().get(SentryConstants.CHILD_KEY);
		if (childObject == null || !(childObject instanceof ISpan)) {
			logger.warn("Start a Sentry child first.");
			return null;
		}
		
		ISpan child = (ISpan) childObject;
		child.finish();
		getContext().getData().remove(SentryConstants.CHILD_KEY);
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Runtime_FinishChild";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
