// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package sentry.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the Sentry module

	/**
	* A JSON structure which will be used to initialize Sentry.
	* Be sure to include the attributes:
	*  - "dsn" always required
	*  - "defaultIntegrations" required to be false.
	*  - "environment" is recommended (dev/test/accp/whatever)
	* 
	* E.g:
	* { "dsn": "http://599381cc1ab84b1baca53776691330af@mx-sentryhost.westeurope.cloudapp.azure.com:9000/3", "environment": "dev", "debug": true, "defaultIntegrations": false }
	*/
	public static java.lang.String getSentryConfig()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Sentry.SentryConfig");
	}
}